name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-22.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install RPM & Pacman (on Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update &&
          sudo apt-get install --no-install-recommends -y rpm libarchive-tools libopenjp2-tools

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build renderer (Vite)
        run: yarn build

      - name: Build Electron main process
        run: yarn electron:build-main

      - name: Build Electron app
        run: npx electron-builder --config electron-builder.yml --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: YesPlayMusic-${{ matrix.os }}
          path: |
            dist_electron/*.dmg
            dist_electron/*.exe
            dist_electron/*.AppImage
          if-no-files-found: ignore
